eventmachine/eventmachine

index.html

Hello,
The value of the font-family property is potentially not what was intended: when wrapped in quotation marks, it is treaded as a single typeface name, not as a list of alternatives.
Regards,
Ivan

"Helvetica,Arial,FreeSans"

---

ext/cmain.cpp

In Windows the open function opens files in text mode by default which can cause problems with binary files.   See:
http://msdn.microsoft.com/en-us/library/z0kc8e3z.aspx
http://msdn.microsoft.com/en-us/library/ktss1a9b.aspx

Fix file uploads in Windows.

---

ext/project.h

Fix issue #561 
Use rb_w32_* functions to handle both files and sockets

Fix closing files and sockets on Windows

---

ext/fastfilereader/mapper.cpp

There seems to be a typo when closing the hFile in mapper.cpp.  Instead of setting the hFile, the mapping handle was being set again.

Set file handle to INVALID_HANDLE_VALUE after closing the file.

---

ext/em.cpp

It doesn't look useful to keep this around?

Remove EventMachine_t::Popen code marked by ifdef OBSOLETE

---

ext/em.cpp
ext/em.h
tests/test_many_fds.rb

Fixes #501
On Ruby 1.9.1 and up, we use `rb_fd_select` and friends to get automatically resized `fd_set`s.  This should transparently provide correct behavior for `select` even when fds exceed `FD_SETSIZE` (1024).
On Ruby 1.8.7 and 1.9.0, we use stubs that warn to stdout whenever anyone tries to `FD_SET`, `FD_CLR`, `FD_ISSET`, or `select` an fd >= `FD_SETSIZE`.  This behavior isn't correct, in that it's noisy and doesn't do anything useful with the high FDs.  But it's better than the current behavior, which is undefined and usually crashes with an unrelated assert or heap corruption after the first high FD.
There's another branch [here](https://github.com/piki/eventmachine/blob/backport-rb-fd/ext/rbselect.impl) that backports the rb_fd_* API.  I've only tested that branch on Debian …

Use the rb_fd_* API to get autosized fd_sets

---

.travis.yml
ext/em.cpp
ext/em.h
ext/extconf.rb
ext/project.h

Based on clock_gettime from #496 with support for Mac OS X based on https://developer.apple.com/library/mac/qa/qa1398/_index.html

Use clock_gettime and mach_absolute_time to make GetRealTime monotonic

---

ext/em.cpp
tests/test_connection_write.rb

This fixes bug #524.
Added a new unit test which fails in current version of EM, but passes with the included fix to em.cpp.

Avoid calling Write() if SelectForWrite() value has changed

---

ext/extconf.rb
ext/fastfilereader/extconf.rb

@tmm1 think I found the mkmf bug.
Seems like it depends the order of `try_link` checks. `have_devel?` is check and cached on the first `try_do` call.
https://github.com/ruby/ruby/blob/4b8df18e0d6ef54f93219eb34b7151a79810bafc/lib/mkmf.rb#L455-L460
However, `try_do` maybe called within the scope of `try_ldflags` which changes `$LDFLAGS` for the duration of the scope.
https://github.com/ruby/ruby/blob/4b8df18e0d6ef54f93219eb34b7151a79810bafc/lib/mkmf.rb#L640-L644
If this was the first call to `try_do`, `have_devel?` will incorrectly test with incorrect `$LDFLAGS` and crash immediately.
My work around was to eager check `have_devel?` Not sure how to fix upstream.
Closes #505.

Workaround mkmf devel check bug

---

README.md

Cool.io is retired and http://coolio.github.io/ points visitors towards Celluloid.

Update alternatives section of README

---

lib/em/pure_ruby.rb

Running rackup on a thin + synchrony sinatra app:
```
[!]You shold install `padrino-helpers' gem if you want to use kaminari's pagination helpers with Sinatra.
[!]Kaminari::Helpers::SinatraHelper does nothing now...
>> Thin web server (v1.3.1 codename Triple Espresso)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:9940, CTRL+C to stop
/Users/noice/.rvm/gems/ruby-1.9.3-p194/gems/eventmachine-1.0.0.beta.3/lib/em/pure_ruby.rb:393:in `open_loopbreaker': Unable to bind Loopbreaker (RuntimeError)
from /Users/noice/.rvm/gems/ruby-1.9.3-p194/gems/eventmachine-1.0.0.beta.3/lib/em/pure_ruby.rb:306:in `run'
from /Users/noice/.rvm/gems/ruby-1.9.3-p194/gems/eventmachine-1.0.0.beta.3/lib/em/pure_ruby.rb:61:in `run_machine'
from /Users/noice/.rvm/gems/ruby-1.9.3-p194/gems/eventmachine-1.0.0.b …
```

em/pure_ruby: Unable to bind Loopbreaker (RuntimeError) on OS X (Use 127.0.0.1 instead of localhost in em/pure_ruby)

---

ext/rubymain.cpp

The build errors on MacRuby because of an invalid conversion from 'const void *' to 'void *'. This pull request fixes it.

Fix compilation under MacRuby

---

lib/em/protocols/httpclient.rb
tests/test_httpclient.rb

I added chunked transfer coding support to the HttpClient class, to support Faye when running behind nginx/thin.  I added a test to cover the changes as well.  Let me know if you have any questions about the code.

Chunked transfer coding support

---

lib/eventmachine.rb

Not sure what the support policy is for 1.8.7, but I ran into a case where the EM thread enters a busy loop and uses ever-increasing memory if EM.run happens to be called from an exception handler. Here is a minimal repro:
https://gist.github.com/manlon/6058884
The behavior or $! seems fixed in ruby 1.9 but it is easy enough to work around here.

prevent busy loop in ruby 1.8.7 exception handling

---

ext/cmain.cpp
ext/ed.cpp
ext/em.cpp
ext/em.h
ext/eventmachine.h
ext/rubymain.cpp

This controls the number of calls to `accept(2)` done in one turn in the loop. The default value is `10`, like before, so it won't change the default behaviour of EM.
The purpose of this it to prevent EM from accepting more connections than it can handle. 
My end goal is to set this to `1` in Thin.
Also add EM.get_simultaneous_accept_count to retreive the value.
If necessary, I can port my changes to the Java backend. Let me know.
/cc @raggi

Add support for EM.set_simultaneous_accept_count(<int>).

---

ext/em.cpp

fixes #522 
confirmed `kill -TERM` works against a kqueue reactor loop after this patch using the repro in https://github.com/eventmachine/eventmachine/issues/522#issue-37535399
```
tmm1@tmm1-air ~/code/eventmachine (loopbreak-at-halt*) $ ruby -Ilib -r eventmachine test.rb
30227
timer
SIGTERM: 1423556870.274626
shutting down: 1423556870.274733
```
/cc @piki

Signal loopbreaker during halt

---

.travis.yml
ext/em.cpp
ext/em.h
ext/extconf.rb

fixes leak reported in https://github.com/eventmachine/eventmachine/issues/585#issuecomment-73646276
originally introduced in https://github.com/eventmachine/eventmachine/pull/502
/cc @piki @sodabrew

Fix fdset memory leak

---

lib/em/protocols/smtpclient.rb
tests/test_smtpclient.rb

The DATA command of the SMTP protocol is terminated by a `\r\n.\r\n`. In order to allow for lines starting with a period or containing only a period, the protocol defines an escape mechanism. From [Section 4.5.2 of RFC5321](https://tools.ietf.org/html/rfc5321#section-4.5.2):
> Before sending a line of mail text, the SMTP client checks the first character of the line.  If it is a period, one additional period is inserted at the beginning of the line.
`EM::Protocols::SmtpClient` currently doesn't do this, and messages that contain the string `\r\n.\r\n` somewhere in the body will be truncated by SMTP servers. This is something we have encountered in the wild.
This PR does a few things:
1. Add `:message` as an additional option to SMTP client. This accepts a string that is a valid RFC2822 …

SmtpClient: Properly escape leading periods in DATA

---

lib/em/protocols/smtpclient.rb
tests/test_smtpclient.rb

Bug: emails sent using `:body` and `:headers` do not have leading dots properly escaped. This PR fixes that. See "Reasoning" below for more info.
The `EM::Protocols::SmtpClient` `:body` and `:headers` parameters now escape leading dots on new lines.
Given the following message passed in as the `:body`
```
Hello
...world!
```
**Old behavior:** The message would be sent as-is. The recipient would see
```
Hello
..world!
```
**New behavior:** The leading dot in the second line would be escaped. The recipient would see
```
Hello
...world!
```
**Required updates to code:** If you knew about this issue and were working around it by manually escaping leading dots in data you passed to `:body` or `:headers`, you need to stop doing so to prevent double escaping. 
cc/ @sodabrew 
While discussing …

SmtpClient: Unconditionally escape leading dots

---

ext/em.cpp

So as not to share them with children, and in particular not fail
to reopen on restart if a child is still around.
This is meant to fix a sensu-client issue (https://github.com/sensu/sensu/issues/862) where the process fails to come back up due to a child that keeps the socket.

Open datagram sockets with CLOEXEC.

---

ext/ed.cpp
ext/ed.h
ext/em.cpp
ext/extconf.rb

Where possible and supported by the operating system, pass creation-time flag arguments that create close-on-exec file descriptors. On platforms (e.g. OS X) that don't support pipe2(2), accept4(2), or SOCK_CLOEXEC, fall back to creating non-close-on-exec descriptors.
Based on patches by Greg Brockman, Patrick Collison

Create file descriptors with O_CLOEXEC where possible

---

tests/test_ltp2.rb

Adapt the test case from #32 to LineText2.
Resolves #32.

Test to show that LineText2 preserves whitespace and newlines

---

ext/ed.cpp
ext/ed.h
ext/em.cpp

This PR implements the patch from #51. Tested on Mac OS X 10.10.4, where the original bug still occurs and the proposed patch resolves it.
Resolves #51, #176, #372, #401.

Postpone ArmKqueueWriter until all events are processed

---

README.md
lib/em/completion.rb

Hyphenated a compound adjective. Corrected “it’s” to “its”.

Two tiny tweaks for grammar

---

ext/em.cpp

Use WSAStringToAddress in lieu of inet_pton for IPv6 address detection on Windows

---

ext/rubymain.cpp

raise on unsupported EM.epoll=true and EM.kqueue=true
Follows up on 9af9406 and #638

Restore silent-fail on unsupported EM.epoll and EM.kqueue

---

ext/ed.cpp
ext/ed.h
ext/em.cpp
ext/em.h
ext/project.h
ext/rubymain.cpp
tests/em_test_helper.rb
tests/test_ipv4.rb
tests/test_ipv6.rb

Resolves #595 by merging and improving upon ibc/eventmachine-le#27 and ibc/eventmachine-le#28
With thanks to @mpalmer for the getaddrinfo implementation in eventmachine-le.

Switch from gethostbyname to getaddrinfo, support IPv6 addresses on Windows

---

lib/em/queue.rb
tests/test_queue.rb

The existing EM::Queue implementation uses push and shift to shuffle the queued items through an array. Unfortunately, a shift followed by a push has linear time complexity in the size of the array, making queue operations very expensive for long queues.
The patch replaces the @items array with two separate arrays @sink for pushing elements into it and @drain for shifting out elements. This ensures that both push and shift get amortized constant time complexity.
In addition, the patch introduces a test that demonstrates the performance issues. For me, the new test passes with both Queue implementations, but takes minutes with the old implementation and much less than a second with the new implementation.

Reimplement Queue to avoid shift/push performance problem

---

lib/eventmachine.rb
tests/test_defer.rb

In the current implementation, if a deferred thread raises an exception while the main thread is executing a very indiscriminate rescue block (e.g., Logger::LogDevice.write) the error may be handled improperly.  In the case of the LogDevice, it will get swallowed up entirely never to be seen again.  This is a bad thing.

Handle deferred exceptions in reactor thread

---

.gitignore
ext/cmain.cpp
ext/em.cpp
ext/em.h
ext/eventmachine.h
ext/rubymain.cpp
lib/em/pure_ruby.rb
lib/eventmachine.rb
tests/test_basic.rb

Currently, eventmachine will stop when a handler raises an exception in its unbind method. This is an intended feature for when the eventmachine reactor is being stopped, as it is undesirable to keep the reactor running when exceptions are being thrown while connections are being unbound. 
This however does cause issues when exceptions are raised in unbinds when eventmachine is not being stopped.
This fix adds a method to the eventmachine cpp module which enables you to check wether or not the reactor is being stopped. Consequently the raising of an exception during an unbind will only resort in a reactor stop if it was already being stopped.
We implemented this locally for a project, tested it and it seems to be working well. Granted, this is only necessary if handler code implements …

Fix to prevent event machine from stopping when a raise is done in an unbind.

---

ext/pipe.cpp
ext/project.h

The doc clearly show that these should be available https://msdn.microsoft.com/en-us/library/windows/desktop/ms738520(v=vs.85).aspx
... AHA! The headers are coming from MingW, and until recently did not provide these values.
http://sourceforge.net/p/mingw-w64/mailman/message/33056995/

Older MinGW in the Ruby Dev Kit does not define the getaddrinfo hints

---

ext/em.cpp

- create new function open_datagram_socket_with_reuseaddr
- the SO_REUSEADDR flag needs to be set before we call the bind on the socket
- add the support to be able to set_sock_opt with SO_BINDTODEVICE
- this takes in a struct with an interface name set inside of it

Allow reusing of datagram socket/setting bind device

---

.travis.yml
ext/ed.cpp
ext/em.cpp
ext/em.h
ext/extconf.rb

Resolves #661 by detecting OpenSSL in the default MacPorts and HomeBrew paths.

Try more ways to detect OpenSSL, including MacPorts and HomeBrew

---

ext/cmain.cpp
ext/rubymain.cpp
ext/ssl.cpp
ext/ssl.h
lib/em/connection.rb
tests/test_ssl_extensions.rb
tests/test_ssl_protocols.rb

Both Ruby OpenSSL and EventMachine-LE use ssl_version, so we should too.
And protocols sounds too much like NPN / ALPN which are TLS extensions required for SPDY and HTTP/2.0.

Rename SSL protocols field to ssl_version for consistency

---

ext/fastfilereader/rubymain.cpp
lib/em/pool.rb
lib/em/protocols/line_and_text.rb
lib/em/threaded_resource.rb

Don't raise/rescue Exception classes, use StandardError instead.
https://robots.thoughtbot.com/rescue-standarderror-not-exception
https://www.relishapp.com/womply/ruby-style-guide/docs/exceptions
http://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby/10048406#10048406

Replace Exception class with StandardError

---

ext/ed.cpp

If EPROTO does not exist define it as EINTR
OpenBSD does not have EPROTO: https://sourceforge.net/p/sshguard/mailman/message/21247557/
Works, tried on 1.2.dev.2 and 1.0.9.1.

Fix build on OpenBSD

---

ext/extconf.rb
ext/fastfilereader/extconf.rb

We had to replace `-shared` with `-bstatic` + `-bdynamic` in order to get EM (>= 1.0.9.1) to compile/build/install on AIX, using the XLC compiler. AFAIK GCC should never be used.

Fix compilation on AIX (w/ XLC)

---

ext/ed.cpp

Previously, calls to close now were ignored if a close was scheduled for after we finish writing. This was problematic in any case where a graceful close was scheduled, but the send buffer might never be consumed, for example:
- stuck TCP connections
- extremely slow readers

Close socket on close_connection even after close_connection_after_writing

---

lib/em/pure_ruby.rb

This pull request:
- Moves `schedule_close()` to `Selectable` (fixing EM socket `close()`)
- No-op stubs `set_pending_connect_timeout()` to allow some software/libraries to work with the pure Ruby EM reactor until it is properly implemented
- Fixed `close_connection()` to allow closing a nonexistent connection (matching C reactor)

Pure Ruby EM fixes

---

.gitignore
ext/rubymain.cpp
lib/em/pure_ruby.rb
lib/eventmachine.rb
rakelib/test_pure.rake
tests/em_test_helper.rb
tests/test_pure.rb
tests/test_ssl_dhparam.rb
tests/test_ssl_ecdh_curve.rb
tests/test_ssl_extensions.rb
tests/test_ssl_protocols.rb
tests/test_ssl_verify.rb

This pull request adds SSL/TLS support to the pure Ruby EM implementation.
@amdprophet & I went into the belly of the beast that is em/pure_ruby. The pure Ruby implementation leaves much to be desired, but it's a start!
```
$ rake test_em_pure_ruby                                         
EM Library Type: pure_ruby
Loaded suite /home/portertech/.gem/ruby/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader
Started
.........
======================================================================================================================================
omitted. [test_no_dhparam(TestSslDhParam)]
/home/portertech/projects/sensu/eventmachine/tests/test_ssl_dhparam.rb:49:in `test_no_dhparam'
======================================================================================================= …
```

Pure Ruby EM SSL (working start_tls)

---

lib/em/protocols/linetext2.rb
tests/test_ltp2.rb

This mod allows the use of a regular expression as the end-of-line delimiter in the LineText2 protocol.  The set_delimiter method will accept a regular expression and set the end-of-line delimiter appropriately.  Anything passed to the set_delimiter method other than a regular expression will be converted to a string.  A new test to capture the use of a regular express was added.

Add regular expression (regex) support to LineText2 protocol's delimiter

---

README.md

The old link redirects to `http://everburning.com/news/eventmachine-introductions/.html`

Fix incorrect tutorial link in README.md

---

lib/em/pool.rb

I fixed an example code  in EventMachine::Pool
- It was expected to request `100.times`, but it was only one requested
- Exception: `undefined local variable or method i`

Fix to enable to work an example code in EM::Pool

---

ext/em.cpp

It was possible that a write was planned to happen but the socket got closed
in the meantime. This would lead to a serious error as it would then attempt
to write on closed socket (-1 socket) and crash.
To be more specific, the error I got at the application was:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: arm kqueue writer failed on -1: Bad file descriptor
```
It's not clear to me where and how to write a spec for this (this only manifests on a KQUEUE system), please let me know how to proceed.

Fix deregistering descriptor when using KQUEUE

---

eventmachine.gemspec
java/src/com/rubyeventmachine/EmReactor.java
lib/jeventmachine.rb

On Jruby, when starting a tcp server locally using the 0 port argument (to select a random port), I was later trying to discover what port it was on by calling: `Socket.unpack_sockaddr_in( EM.get_sockname( signature ) ).first`
Because the server doesn't get added to the Connections HashMap, I was getting an NPE. This PR appears to address it in my local tests, and it favors entries in Connections and falls back to the Acceptors.
I also added a couple things to make java builds friendlier, and a missing constant that was also causing me some pains.
Things appear to install and run fine, but when I try to run tests (using JRuby 9.1.2.0), I end up getting many errors about too many files being open. I could crank up my ulimit (it's already at 512), but I'm not sure how much further I need to …

Use Acceptors to get peer and sock names if not present in Connections

---

ext/ed.cpp
ext/em.cpp
ext/em.h

This is required on Solaris for correct lookups. Resolves #745

Set the socktype field for getaddrinfo

---

ext/rubymain.cpp
tests/test_file_watch.rb

Addresses #512
Some how the runtime error thrown in evma_unwatch_filename was not caught and EM crashed with std::runtime_error. A Simple patch to fix this by throwing a ruby exception instead.
Not sure if this is the correct fix but at least the ruby exception can be caught and handled further.

Raise a ruby exception for InvalidWatchSignature

---

ext/binder.cpp
ext/binder.h
ext/ed.cpp
ext/ed.h
ext/pipe.cpp

In C++11 and later, destructors are marked `noexcept(true)` by default.  All throws become calls to `terminate()`.  To enable the original intent of the throw, such destructors (and if virtual, those of its parent classes) need to be explicitly marked `noexcept(false)` when compiled in a dialect >= C++11.

Allow destructors to throw when compiling in >= C++11

---

ext/em.cpp
ext/em.h
tests/test_exc.rb

I experienced a segfault similar to #765, #758 and #761, debugging the code I found that the problem was caused by a double free of the a `EventableDescriptor`.
In detail `EventMachine_t::_CleanupSockets()` was calling the `EventableDescriptor` destructor that triggers the `Connection#unbind` callback. The problem is that when the callback raises an exception, it stops the EventMachine and eventually calls the `EventMachine_t` destructor that attempts to destroy the same `EventableDescriptor` since the `EventMachine_t::_CleanupSockets()` function hasn't yet cleaned up the Descriptors vector.
The workaround used was very crude but it works, it delays the destruction of the `EventableDescriptor` to after they are removed from the `Descriptors` vector.

Fix segfault when an Exception is raised from unbind callback

---

tests/test_threaded_resource.rb

Fixes:
~~~
$ ruby -Itests tests/test_threaded_resource.rb 
tests/test_threaded_resource.rb:1:in `<main>': uninitialized constant Test (NameError)
~~~

Require 'em_test_helper'

---

ext/em.cpp
ext/em.h
ext/rubymain.cpp
java/src/com/rubyeventmachine/EmReactor.java
lib/eventmachine.rb
tests/test_timers.rb

In the Sensu project we've added support for scheduling timers using cron syntax. In https://github.com/sensu/sensu/issues/1665 a user reported that they were able to cause an exception in scheduling by configuring a timer that should run on the first of every month.
This pull request seeks to address this exception by using variable types which allow for larger interval values.

Allow for larger values in oneshot timer intervals

---

tests/test_ssl_protocols.rb

Adds checks for whether SSLv3 is available and adds some replacement tests using TLSv1_2

OpenSSL 1.1.0 test updates

---

lib/em/pure_ruby.rb

In ```Connection::error?``` the method ```EventMachine::report_connection_error_status``` is invoked, which does not exist in the pure ruby version, but does exist in the native C++ version.  This PR provides the equivalent pure ruby version of ```EventMachine::report_connection_error_status```

Method report_connection_error_status is missing

---

eventmachine.gemspec

For another example, see [ruby / openssl openssl.gemspec:25](https://github.com/ruby/openssl/blob/5c1c0fa507fc517596041c7bee9aa34172425649/openssl.gemspec#L25).
This allows the RubyInstaller2 runtime files to load the MinGW OpenSSL package before the compile is started.
Also, see <https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers>

Add gemspec metadata for MinGW builds

---

eventmachine.gemspec

Fix for https://github.com/eventmachine/eventmachine/commit/208027e3ea808ddf3b297e2578c148017db2a27f.
On Appveyor, all ruby versions have updated RubyGems.  Saw something similar in a recent ruby/ruby commit.

Fix for old RubyGems

---

ext/ssl.cpp

This change allows more easy debugging of applications that use eventmachine (native mode) with SSL.
Example of the output:
```
139861096265472:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:640:
```

ssl: c++: be verbose about SSL connection errors

---

README.md

Shall we add Travis build status badge because I want to see Travis page casually?
You can see the modified README here.
https://github.com/junaruga/eventmachine/tree/feature/travis-status-badge

Add Travis build status badge to README.

---

lib/em/completion.rb
lib/eventmachine.rb

Adjusts doc/comments for correct parsing.  Note differences in first 'Overview' section.
See
(old) http://www.rubydoc.info/gems/eventmachine/EventMachine/Completion
(new) https://msp-greg.github.io/eventmachine/EventMachine/Completion.html
and
(old) http://www.rubydoc.info/gems/eventmachine/EventMachine/Completion
(new) https://msp-greg.github.io/eventmachine/EventMachine.html
(old) is YARD, (new) is my doc site, which is based on YARD.

Correct EM::Completion doc location [ci skip]

---

.travis.yml

Let me fix this.
Maybe.
* Ruby 1.9.2 on trusty is available.
* rbx-3 on trusty is available.
I referred rspec-core's case.
https://github.com/rspec/rspec-core/blob/master/.travis.yml
https://travis-ci.org/rspec/rspec-core

Update .travis.yml to pass tests.

---

.travis.yml
Gemfile
README.md
docs/GettingStarted.md
ext/cmain.cpp
ext/em.cpp
ext/em.h
ext/eventmachine.h
ext/rubymain.cpp
lib/em/pure_ruby.rb
rakelib/package.rake
tests/test_ssl_protocols.rb
tests/test_timers.rb

EventMachine has a (dynamically adjustable) limit on the number of outstanding timers. To reduce the risk of hitting this limit, we need to see how close we are to the limit. This PR exposes the current number of outstanding timers as `EventMachine::get_outstanding_timer_count`.

Expose outstanding timer count

---

ext/binder.cpp
ext/binder.h
ext/ed.cpp
ext/ed.h
ext/em.cpp
ext/em.h
ext/fastfilereader/mapper.cpp
ext/fastfilereader/mapper.h
ext/fastfilereader/rubymain.cpp
ext/page.cpp
ext/page.h
ext/project.h
ext/ssl.cpp
ext/ssl.h

This resolves the conflict of socket bind() vs std::bind(), as more std:: functions may be introduced in future versions of C++.
Resolves #830

Remove using namespace std; and be explicit with std:: prefixes

---

ext/em.cpp
ext/em.h
ext/extconf.rb

The original epoll_create took a size argument as a hint for how much
kernel space to allocate for events. Since Linux 2.6.8, the size
argument is ignored, but must be greater than zero.
Since we also need to set CLOEXEC on the epoll fd, there is a small
window between epoll_create and fcntl as they are separate function
calls. Since Linux 2.6.27 and glibc 2.9, epoll_create1 accepts the
CLOEXEC argument at creation time to eliminate this gap.
This drops support for epoll on RHEL 5 / CentOS 5, EOL was March 2017.
Resolves #770

Switch from epoll_create to epoll_create1

---

ext/em.cpp
ext/em.h
lib/eventmachine.rb
tests/test_basic.rb
tests/test_pool.rb

Updates #327 to avoid crashing the machine on release.
Reverts #766 as it was not a fix to the root problem.
Fixes #620, #758, #761, #765, #792, #822.

Fix unbind exceptions

---

.gitignore
appveyor.yml
tests/em_test_helper.rb
tests/test_attach.rb
tests/test_basic.rb
tests/test_file_watch.rb
tests/test_httpclient2.rb
tests/test_ipv4.rb
tests/test_ssl_protocols.rb
win_gem_test/Rakefile_wintest
win_gem_test/eventmachine.ps1
win_gem_test/package_gem.rb

This PR changes Appveyor CI to build pre-compiled Windows gems, then uses them for testing all Ruby versions.  To use the build/test system, a new folder (win_gem_test) is added, which contains three files specific to EM.  The packaged gems include a new rakefile and the test files.
All versions are built & tested with the correct version of OpenSSL.
The 2nd commit 'Update Tests for Windows', modifies current tests with 'pends' to allow passing on both 32 & 64 bit, using Ruby 2.0 thru trunk.  Not being that familiar with EM, these should be reviewed.
Current Appveyor build on my fork is [here](https://ci.appveyor.com/project/MSP-Greg/eventmachine/build/25), and passing.

Appveyor - Create Windows pre-compiled gems and test

---

tests/em_ssl_handlers.rb
tests/em_test_helper.rb
tests/test_io_streamer.rb
tests/test_ssl_args.rb
tests/test_ssl_dhparam.rb
tests/test_ssl_ecdh_curve.rb
tests/test_ssl_extensions.rb
tests/test_ssl_methods.rb
tests/test_ssl_protocols.rb
tests/test_ssl_verify.rb

1. Remove global variables
2. All ssl tests use handlers in em_ssl_handlers.rb
3. Utilize native EM parameter passing to handlers
4. Add more asserts for cipher_name where applicable

Add test/em_ssl_handlers.rb

---

lib/em/pure_ruby.rb
tests/test_pure.rb

`EventMachine::add_timer` passes the interval as int, leading to integer division and loss of sub-second intervals in the pure ruby implementation. Fix this by forcing float division.

pure_ruby: Allow sub-second intervals for timers

---

tests/em_ssl_handlers.rb
tests/test_httpclient2.rb

em_ssl_handlers.rb - EMSSLHandlers
1. Use `setup_timeout` from em_test_helper.rb in `#client_server`, which raises an error.  Currently code does not.
2. Add timeout: KWARG to  `#client_server`
test_httpclient2.rb - Add more time to some tests for older Windows intermittent errors.
Build in my fork took almost an hour, which is longer than normal.  Long build times normally correlate with intermittent test failures/errors.  Hence, this hopefully fixes the last of them.

Misc test fixups

---

ext/extconf.rb
ext/fastfilereader/extconf.rb
ext/rubymain.cpp

This allows EventMachine to compile on TruffleRuby.
Although it does not run yet (e.g., `rb_thread_fd_select` is not yet implemented in TruffleRuby).
What's the status of the pure-Ruby backend? That would probably be easier to support than the C++ extension.

Support compiling EventMachine on TruffleRuby

---

tests/test_inactivity_timeout.rb

Still seeing the behavior described in #554 where comm_inactivity_timeout sometimes takes twice the requested timeout value.  The code in the gist linked from there demonstrates the issue for me on multiple machines but only roughly ~5% of the time.
By reducing the timeout values by a factor of 100, it reproduces 100% of the time for me here locally.  Basically what is happening is that you request a timeout of say 15 seconds (15000000 microseconds) the heartbeat to check the inactivity time might arrive when the inactivity time is just under that value but really close e.g. 14998819 microseconds.  I've seen ranges of about 100-3500 microseconds difference.
Another heartbeat to check the inactivity won't be scheduled to arrive until the next interval so this is why it takes double the …

add failing test where comm_inactivity_timeout takes too long

---

ext/ed.cpp
ext/em.cpp
ext/em.h

As discussed in #889, I tried various things but this is the only solution I've found that works.  I've tested it on a bunch of different hardware and it works fine even on very slow devices like the Raspberry Pi Zero.
Fixes #554.

adjust inactivity comparison so it will match nearly equal values

---

lib/em/protocols/line_protocol.rb

I'm having problems with current line_protocol implementation, causing up to 60% of my overall run time to be spent slicing the message buffer. I've change it to use ``String#each_line`` instead of ``slice`` which proves to be 200x faster:
```Ruby
require 'benchmark'
def new_version(size)
buffer = Array.new(size, 'foo 123').join("\n")
buffer.each_line do |line|
if line[-1] == "\n"
else
buffer = line
end
end
end
def original(size)
buffer = Array.new(size, 'foo 123').join("\n")
while buffer.slice!(/(.*?)\r?\n/) do
end
end
Benchmark.bmbm do |x|
x.report('original') { original(100_000) }
x.report('new_version')  { new_version(100_000) }
end
```
```
Rehearsal -----------------------------------------------
original      4.891919   0.103960   4.995879 (  4.993582)
new_version   0.026254 …
```

Improve line_protocol speed

---

eventmachine.gemspec

Hello,
It appears you're no longer maintaining the http://rubyeventmachine.com URL as I get redirected to http://www.inbudapesthotels.com/rubyeventmachinecom/. At least this fixes that in the short term.
Regards,
iain

Website URL appears to no longer be registered

---

lib/em/connection.rb

Resolve #882. I agree that, even though any reasonable implementation should override this method, a debug puts should also be the responsibility of the subclass.

Remove debug puts from base class of EM::Connection

---

.github/workflows/workflow.yml
eventmachine.gemspec
ext/extconf.rb
ext/fastfilereader/extconf.rb
rakelib/package.rake
tests/em_test_helper.rb
tests/test_basic.rb
tests/test_idle_connection.rb
tests/test_inactivity_timeout.rb
tests/test_ipv4.rb
tests/test_pause.rb
tests/test_pure.rb
tests/test_resolver.rb
tests/test_send_file.rb
tests/test_ssl_protocols.rb

Six commits:
1. 'extconf.rb updates' - Some Windows specific, others are update & cleanup for OpenSSL checks
2. 'package.rake - remove devkit on GitHub Actions' - At present, Actions does not have a standard MSYS2 install, and also does not have RubyInstaller devkits (Ruby 2.3 and older).  The devkit paths are enabled by the actions used to load Ruby.
3. 'eventmachine.gemspec - s.metadata["msys2_mingw_dependencies"]' - The metadata tag updates the MinGW OpenSSL package, but the current package (1.1.1) is incompatible with Ruby 2.4, which uses 1.0.2
4. 'test adjustments - darwin, some windows'
5. 'Add GitHub Actions workflow.yml' - tests on Ubuntu & macOS, Ruby 2.2. thru master, Windows Ruby 2.4 thru master.  On all three OS's, older Ruby version use OpenSSL 1.0.2, newer versions use …

Add GitHub Actions

---

lib/em/pure_ruby.rb

This fixes the em/pure_ruby bug highlighted in issue #927 , @sodabrew .

fix intra-iteration element delete bug

---

README.md

celluloid.io does not exist. Lets link to the Github repo instead.

celluloid.io does not exist. Link to github repo instead

---

.github/workflows/workflow.yml

Also adds 'workflow_dispatch', which allows owners/maintainers to start an Actions run of a workflow without a commit or a PR.
Note that there are issues with Ruby 3+ on all platforms

GitHub Actions - add Ruby 3.0

---

.github/workflows/workflow.yml
.gitignore
Gemfile
appveyor.yml
eventmachine.gemspec
ext/extconf.rb
ext/rubymain.cpp
tests/test_io_streamer.rb
tests/test_processes.rb
win_gem_test/eventmachine.ps1

This has several commits.  Most importantly, it updates EM to work with Ruby 3, as changes to Process::Status were needed.
It also updates test_process.rb and various files for local use and testing.
On AppVeyor, it successfully builds a Windows gem for use with Ruby 2.2 thru 3.0, both 64 and 32 bit.

Fixes for Ruby 3, misc

---

.github/workflows/workflow.yml

This PR introduces Ruby 3.1, the current generally available Ruby, to the matrix.
```
1) Error: test_https_get(TestHttpClient2): Test::Unit::TestCase::EMTestTimeout: Test was cancelled after 1 seconds.
/home/runner/work/eventmachine/eventmachine/tests/em_test_helper.rb:45:in `block (2 levels) in setup_timeout'
/home/runner/work/eventmachine/eventmachine/lib/eventmachine.rb:196:in `run_machine'
/home/runner/work/eventmachine/eventmachine/lib/eventmachine.rb:196:in `run'
/home/runner/work/eventmachine/eventmachine/tests/test_httpclient2.rb:122:in `test_https_get'
119:   def test_https_get
120:     omit("No SSL") unless EM.ssl?
121:     d = nil
=> 122:     EM.run {
123:       setup_timeout(CI_WINDOWS_OLD ? 9 : TIMEOUT)
124:       http = silent { EM::P::HttpClient2.connect :host => …
```

CI: Add Ruby 3.1 to matrix

---

README.md

The README currently says:
"EventMachine supports Ruby 2.0.0 through 2.7, JRuby and **works well on Windows** as well as many operating systems from the Unix family (Linux, Mac OS X, BSD flavors)."
This PR removes the upper bound so as not to imply that Ruby 3 is not supported, and adds a note to check for tested versions if interested:
"EventMachine supports Ruby 2.0.0 and later (see tested versions at [.github/workflows/workflow.yml](.github/workflows/workflow.yml)), JRuby, and **works well on Windows**, as well as many operating systems from the Unix family (Linux, Mac OS X, BSD flavors)."
Please note that I am not very familiar with eventmachine, so please verify that my statement is correct.
As some supporting evidence, however, @robbkidd pointed out to me that:
* the gemspec does …

Remove mention of Ruby version upper bound from readme.

---

README.md

Rubydoc docs are now hosted on http://rubydoc.info, `rdoc.info` site is broken.

update Rubydoc documentation URL in the readme

---

.github/workflows/workflow.yml
tests/em_test_helper.rb
tests/test_basic.rb
tests/test_httpclient2.rb
tests/test_idle_connection.rb
tests/test_inactivity_timeout.rb
tests/test_ipv4.rb
tests/test_pause.rb
tests/test_pure.rb
tests/test_send_file.rb
tests/test_threaded_resource.rb

This PR updates the GitHub Actions CI workflow, and all of its jobs should pass now.
* **Drop unsupported `ubuntu-18.04` runner from CI**
GitHub Actions dropped support for ubuntu-18.04 on 2023-04-03:
- https://github.com/actions/runner-images/issues/6002
Although there are benefits to testing with older OS versions—especially given EventMachine's legacy status and the types of projects which are most likely to depend on it—there are also significant costs to maintaining CI for them once GitHub Actions has dropped support.
* **Add newer Ubuntu runners to CI**
Each Ubuntu LTS comes with a different version of OpenSSL, Linux Kernel, etc.  And people are likely to deploy EventMachine applications to any of these versions.  So there is some benefit to testing every Ubuntu LTS release that is …

Update CI matrix

---

.github/workflows/workflow.yml
lib/em/pure_ruby.rb

With these commits, I was able to successfully run `rake test_pure` without any failing tests.

Fix TLS connection of the pure Ruby reactor

---

.editorconfig

I was just using editorconfig settings that seemed sensible for what's already there.  Please change the actual values to whatever seems most suitable to you.  😄 
I suppose I *could* add "compile_commands.json" to my global gitignore... But IMO adding it here is reasonable.

Add .editorconfig for rb, cpp, h files

---

java/src/com/rubyeventmachine/EmReactor.java

Resolves #477, IO waits in Java code checkIO are reduced to at most timerQuantum miliseconds

Fix for #477

---

tests/em_test_helper.rb
tests/test_attach.rb
tests/test_basic.rb
tests/test_ltp.rb
tests/test_ltp2.rb
tests/test_send_file.rb

See any Ruby head CI job's logs.
Will do another PR with lib file updates for the same.

[CI] test files - fix Ruby head 'warning: literal string will be frozen...'

---

.github/workflows/workflow.yml

Add jobs for macOS amd64 (`macos-13`), use `macos-14` instead of `macos-latest` (arm64).
Fixes up issues with old RubyGems and installing tools/openssl for **only** Windows Ruby 2.3.

workflow.yml - use setup-ruby's `bundler-cache: true`, misc

---

tests/test_httpclient2.rb
tests/test_pure.rb

1. Commit fixes Windows test failures by increasing the timeout values.  These three tests also fail locally.
2. Add `# frozen_string_literal: true` to the two test files.
3. Adds a variable `@host = '127.0.0.1` and replaces in each file.  We don't need to create so many strings...

[CI] Windows test fixes - test_httpclient2.rb & test_pure.rb

---

tests/test_httpclient2.rb

Just failed in my fork.  Friday afternoon is a busy time for GHA...
Failing test makes an external connection to google.com, and sends two requests.
In Puma, we've jumped thru hoops trying to get CI stable when the GHA runners are busy.  Most issues are blocking related.  Regardless, what never fails locally often fails intermittently on GHA.

[CI] test_httpclient2.rb - fix intermittent failures on GHA

---

.github/workflows/workflow.yml
eventmachine.gemspec

Most deployments will be to linux servers, and EventMachine *is* still maintaining *some* support for old versions of ruby.  So this still keeps up to four EOL ruby builds for ubuntu, but _only_ for ruby versions that went EOL _after_ that version of ubuntu was first released.
This fixes #997, following the verbose proposal I made in my comment on that ticket. 🙂

Remove most EOL rubies from the build matrix

---

ext/extconf.rb
ext/fastfilereader/rubymain.cpp
ext/ssl.cpp
tests/test_ssl_dhparam.rb

Six commits (can be squashed):
**Ruby 3+ & OpenSSL 3 fixes** - Use SSL_get1_peer_certificate with OpenSSL 3, add rb_undef_alloc_func(Mapper); for Ruby 3 warning
**Use SSL_CTX_set_dh_auto** - used when needed and available.  Updated tests/test_ssl_dhparam.rb
**Update Actions workflow** - macOS 11, windows 2022
**Test fixes/updates, add next_public_port** - some fixes are needed for windows-2022 image, updated 'find an open port' handling
**Update Actions workflow - Ubuntu 22.04, OpenSSL 3** - Add Ubuntu 22.04 Ruby 3.1 & head, both of are compiled with OpenSSL 3.0.x.  Both are passing, along with local testing.
When compiling with OpenSSL 3, there are some deprecation warnings.  Previously, OpenSSL had two API's for many crypto operations.  The older API is deprecated in OpenSSL 3.  Also, …

Allow EM to build with OpenSSL 3, minor CI and test fixes

---

lib/em/protocols/httpclient.rb

In practice, I don't think either of these really matter:
* `@data` will just be reassigned in `#receive_data`'s `:base` clause
* `@content` should be reassigned (to non-frozen) by the earlier if/eslif clauses, prior to being mutated by the `else` clause.
But, for consistency, documentation, and in case this is subclassed, we should ensure that these vars are always mutable buffers.
This is a followup to #1003.

Add str.dup to httpclient, for consistency
