ext/rubymain.cpp
Simpler version of PR #539 by Eric Promislow <ericp@activestate.com>
=> Catch failure to fork

.travis.yml, eventmachine.gemspec, ext/extconf.rb, lib/em/connection.rb, lib/eventmachine.rb, rakelib/package.rake, tests/test_attach.rb, tests/test_basic.rb, tests/test_connection_count.rb, tests/test_epoll.rb, tests/test_iterator.rb, tests/test_kb.rb, tests/test_process_watch.rb, tests/test_processes.rb, tests/test_resolver.rb, tests/test_ssl_args.rb, tests/test_ssl_methods.rb, tests/test_ssl_verify.rb, tests/test_threaded_resource.rb
Working through Travis failures seen in 3349891
=> Update build deps

tests/test_resolver.rb
Cherry picked #490 / rebased onto current master.
=> Add some basic tests that the DNS resolver isn't leaking timers

lib/em/protocols/smtpserver.rb
Hi, guys. Would you like to merge some little bug fixes for smtpserver.rb I made several years ago? I'm going to destroy my eventmachine fork in two weeks. That means, my little work on smtpserver.rb is going to be void, if it'll still unmerged, since no one is interested in it. ;-)
Greetings,
Averell
=> Some small bug fixes in smtpserver.rb

CHANGELOG.md, ext/rubymain.cpp, tests/em_test_helper.rb, tests/test_basic.rb, tests/test_process_watch.rb, tests/test_ssl_methods.rb, tests/test_ssl_verify.rb
The Rubinius work from #551 is rebased here.
=> Rubinius popen and test fixes

java/src/com/rubyeventmachine/EmReactor.java, java/src/com/rubyeventmachine/EventableChannel.java, java/src/com/rubyeventmachine/EventableDatagramChannel.java, java/src/com/rubyeventmachine/EventableSocketChannel.java, lib/jeventmachine.rb, tests/test_pause.rb
- add gather write
- add pause/resume
- add get_outbound_data_size
=> Jruby improve a bit

lib/em/protocols/linetext2.rb
=> Unroll linetext2's tail recursion to avoid stack level too deep

ext/binder.cpp, ext/binder.h, ext/cmain.cpp, ext/ed.cpp, ext/ed.h, ext/ssl.cpp
This will resolve #612 and is more correct by definition.
=> Use uintptr_t instead of unsigned long for binding pointers

ext/cmain.cpp, ext/ed.cpp, ext/em.cpp, ext/em.h, ext/eventmachine.h, ext/rubymain.cpp, lib/eventmachine.rb
This is a bigger refactor than #202 but I think it is cleaner overall.
Resolves #201, #202.
=> Crank the machine from Ruby space when running Rubinius

ext/ed.cpp, ext/em.h, ext/extconf.rb, ext/fastfilereader/extconf.rb, ext/fastfilereader/mapper.cpp, tests/em_test_helper.rb, tests/test_file_watch.rb
=> Detect the Solaris Studio compiler

ext/em.cpp
Make sure that any failure which could have been a system error is thrown with `strerror(errno)` included in the body. That'll help for #136 to make sure the end user knows what actually caused the failure.
For example, if you open too many connections, the error might be:
```
#<EventMachine::ConnectionError: unable to resolve server address>
```
By including the strerror text, the exception will give a clue to the real problem:
```
#<EventMachine::ConnectionError: unable to resolve server address: Too many open files>
```
Resolves #136
=> Throw a message with strerror included

.travis.yml, lib/eventmachine.rb
Possible solution to #642. Also seeing if Travis can test both JRuby 1.7 and 9000 for us.
=> JRuby use io.fileno

lib/eventmachine.rb, tests/test_basic.rb, tests/test_fork.rb
=> New method cleanup_machine factors out cleanup code from EM.run

ext/ed.cpp, ext/ssl.cpp
Resolves #544 - Cherry picked from EventMachine-LE fb8ce892d4d5f2dda1400a58d4651d865e746713
=> Fix SSL error when the server replies a TLS Alert to our ClientHello

ext/extconf.rb
=> Test compiler flags with the C++ compiler and add them to CXXFLAGS

ext/ed.cpp, ext/em.cpp, ext/em.h, ext/extconf.rb, ext/fastfilereader/extconf.rb, ext/fastfilereader/mapper.cpp, ext/pipe.cpp, ext/rubymain.cpp, ext/ssl.cpp, lib/eventmachine.rb, tests/em_test_helper.rb, tests/test_file_watch.rb
Cherry picks from master per #673
=> Backports for EventMachine 1.0.9

eventmachine.gemspec, ext/extconf.rb, rakelib/package.rake
With thanks again for the great tools to @kou and @larskanis.
=> Use rake-compiler-dock to cross-compile gems for Windows

lib/em/iterator.rb, tests/test_iterator.rb
eg `EM::Iterator.new(proc{ queue.pop || EM::Iterator::Stop })`
Would welcome any comments on this.  The `EM::Iterator::Stop` is kinda weird - a simpler API might be to just return `nil`, but that would assume that no-one's interested in processing nils in their iterator.
=> Support proc-sources in EM::Iterator

ext/ed.cpp
=> Use struct sockaddr_in6 to be able to accept both IPv4 and IPv6 addresses

.travis.yml, ext/ed.cpp, ext/em.cpp, ext/em.h, tests/test_basic.rb
=> Use gai_strerror to get the failure string from getaddrinfo

ext/ed.cpp, ext/ed.h, ext/rubymain.cpp
=> Throw strerror(errno) when getsockname or getpeername fail

lib/em/pure_ruby.rb
=> Add get_sockname to Pure Ruby Reactor

ext/extconf.rb
Windows libraries are renamed in OpenSSL 1.1.0.
=> Update extconf.rb to allow MinGW builds with OpenSSL 1.1.0

java/src/com/rubyeventmachine/EmReactor.java
=> Add EM_PROTO_SSL/TLS definitions to the Java Reactor, fixes #773

ext/cmain.cpp, ext/eventmachine.h
=> Update to large timers to expand the type for the intermediate C function

java/src/com/rubyeventmachine/EmReactor.java
=> Use long for larger values in oneshot timer intervals

lib/jeventmachine.rb
=> JRuby: return zero when sending data to a closed connection

ext/cmain.cpp, ext/ed.cpp, ext/ed.h, ext/eventmachine.h, ext/rubymain.cpp, tests/test_keepalive.rb
=> Make EventMachine support keepalive

Gemfile, appveyor.yml, eventmachine.gemspec, lib/em/protocols/httpclient.rb, lib/em/protocols/httpclient2.rb, tests/em_test_helper.rb, tests/test_basic.rb, tests/test_channel.rb, tests/test_exc.rb, tests/test_file_watch.rb, tests/test_httpclient2.rb, tests/test_keepalive.rb, tests/test_pure.rb, tests/test_resolver.rb, tests/test_ssl_dhparam.rb, tests/test_ssl_ecdh_curve.rb, tests/test_ssl_methods.rb, tests/test_ssl_protocols.rb, tests/test_ssl_verify.rb
Rebase of #837 which is a PR of #799.
=> AppVeyor updates and tests passing for Ruby 2.0 - 2.5

ext/cmain.cpp, ext/eventmachine.h, ext/rubymain.cpp, lib/em/connection.rb, tests/test_process_watch.rb
This PR provides a way to test if a connection is watch_only.
=> EM::Connection#watch_only?

lib/em/io_streamer.rb, tests/test_io_streamer.rb
Similar to FileStreamer, but for IO objects.  Intended for streaming HTTP request bodies.
=> Added support for streaming IO objects

.travis.yml, eventmachine.gemspec
=> Minimum Ruby 2.0.0

.travis.yml, ext/rubymain.cpp, tests/jruby/test_jeventmachine.rb
Resolves #898.
Update for ruby/ruby#2404 by adapting what SWIG did in swig/swig#1692 with the `VALUEFUNC` ifdef wrapper.
=> Ruby 2.7 updates

.github/workflows/workflow.yml, .gitignore, Gemfile, appveyor.yml, eventmachine.gemspec, ext/extconf.rb, ext/rubymain.cpp, tests/test_io_streamer.rb, tests/test_processes.rb, win_gem_test/eventmachine.ps1
The structure of type rb_data_type_struct is a C structure, so it might need to be wrapped in `extern "C"` to get the right behavior. #948 cc @MSP-Greg
=> Try extern C for PR 948

docs/GettingStarted.md
Change `lets` to `let's` and `Is` to `is`.
=> Fix several typos in GettingStarted.md.

lib/em/pure_ruby.rb
Because `@timers` is a SortedSet (implemented using rbtree) it can't be modified during iteration.  Some work had already been done to fix deletion of timers during iteration, but this solves the addition of new oneshot timers.
=> Fix pure ruby Reactor#install_oneshot_timer

.github/workflows/workflow.yml, Gemfile, lib/em/pure_ruby.rb, lib/eventmachine.rb, tests/test_ssl_inline_cert.rb
This is a collection of fixes for making the test suite pass using the pure ruby implementation.  I started by splitting these each into their own atomic PRs, but there was quite a bit to do than I originally realized.  So I wanted to have a single PR that fixes all of the tests _and_ enables the pure ruby workflow in GitHub Actions.
Please note: this PR includes the following others:
* #991
* #992 
And, although this gets the pure ruby CI passing, the regular CI suite is not currently passing.  This PR needs to be merged first before the full build can pass.
* #995
=> Fix pure ruby tests

tests/em_test_helper.rb, tests/test_httpclient2.rb, tests/test_resolver.rb, tests/test_threaded_resource.rb
It remains to be seen if this actually fixes the worst offenders among the flaky tests... :)
=> Adjust flaky timeouts

tests/test_ssl_verify.rb
These all pass now.  I believe they were fixed by 0c0c715 in #993.
=> Run SSL verify tests in pure ruby CI
